use std::sync::Arc;
use parking_lot::RwLock;
use keypaths_proc::{Casepaths, Kp};

#[derive(Debug, Kp)]
#[Writable]
struct SomeComplexStruct {
    scsf: Option<SomeOtherStruct>,
    scfs2: Arc<RwLock<SomeOtherStruct>>
}

#[derive(Debug, Kp)]
#[Writable]
struct SomeOtherStruct {
    sosf: Option<OneMoreStruct>,
}

#[derive(Debug, Casepaths)]
#[Writable]
enum SomeEnum {
    A(String),
    B(Box<DarkStruct>),
}

#[derive(Debug, Kp)]
#[Writable]
struct OneMoreStruct {
    omsf: Option<String>,
    omse: Option<SomeEnum>,
}

#[derive(Debug, Kp)]
#[Writable]
struct DarkStruct {
    dsf: Option<String>,
}


impl SomeComplexStruct {
    fn new() -> Self {
        Self {
            scsf: Some(SomeOtherStruct {
                sosf: Some(OneMoreStruct {
                    omsf: Some(String::from("no value for now")),
                    omse: Some(SomeEnum::B(Box::new(DarkStruct {
                        dsf: Some(String::from("dark field")),
                    }))),
                }),
            }),
            scfs2: Arc::new(
                RwLock::new(
                    SomeOtherStruct {
                        sosf: Some(OneMoreStruct {
                            omsf: Some(String::from("no value for now")),
                            omse: Some(SomeEnum::B(Box::new(DarkStruct {
                                dsf: Some(String::from("dark field")),
                            }))),
                        }),
                    }
                )
            )
        }
    }
}
fn main() {
    // For Option fields, use _fw() methods which return WritableOptionalKeyPath
    // These can be chained with .then() for nested Option access
    // For enum cases, use the generated _fw() method from Casepaths macro
    // For Box<DarkStruct>, we need to unwrap the Box first using for_box(), then access dsf
    let dsf_kp = SomeComplexStruct::scsf_fw()
        .then(SomeOtherStruct::sosf_fw())
        .then(OneMoreStruct::omse_fw())
        .then(SomeEnum::b_fw())  // Generated by Casepaths macro
        .for_box()  // Unwrap Box<DarkStruct> to DarkStruct
        .then(DarkStruct::dsf_fw());

    let mut instance = SomeComplexStruct::new();
    
    // get_mut() returns Option<&mut String> for WritableOptionalKeyPath
    if let Some(omsf) = dsf_kp.get_mut(&mut instance) {
        *omsf = String::from("This is changed 🖖🏿");
        println!("instance = {:?}", instance);
    }
}
